import {
  animalistic,
  balsamsOil,
  berries,
  drinks,
  flowers,
  fruits,
  gourmand,
  green,
  mushrooms,
  natural,
  nuts,
  objects,
  rare,
  resins,
  spices,
  synthetics,
  vegetables,
  woods,
} from "./nots";

import type { PerfumesTierType } from "./constants";
import { storyB } from "./stories";

//============ флаконы ========================

const reliqviaBottle = "../public/bottles/brands/sorcinelli/reliqvia-2.jpg";
const lavsBottle = "../public/bottles/brands/sorcinelli/lavs-2.jpg";
const ventoForteBottle =
  "../public/bottles/brands/sorcinelli/vento-forte-2.webp";
const bombardeBottle = "../public/bottles/brands/sorcinelli/musique-2.jpg";
const fantomasBottle = "../public/bottles/tier-b/fantomas.jpg";

const inexcusableBottle = "../public/bottles/brands/toskovat/inexcusable-evil.webp";
const birthdayBottle = "../public/bottles/brands/toskovat/last-birthday-cake.webp";

const principalitiesBottle = "../public/bottles/brands/caeleste/principalities.webp";

const NotIMG = "../public/bottles/not-bottle.webp";

//================ Вайб ====================

const imgVibe = "../public/vibe/test-room.jpg";

//================ Тиры ====================

const perfumesTierB: PerfumesTierType = [
  {
    titlePage: "Эксперементальный уровень",
    descriptionPage: "Необычные парфюмы",
    listPerfumes: [
      {
        brand: "Filippo Sorcinelli",
        perfumeName: "Reliqvia",
        promoText: "Готический церковный ладан",
        imagePerfume: reliqviaBottle,
        price01ml: 0,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 50,
        price10ml: 100,
        priceFull: 190,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Пачули", src: green.patchouli },
            { name: "Ладан", src: resins.incense },
            { name: "Кашмеран", src: synthetics.cashmeran },
            { name: "Гваяк", src: woods.guaiacWood },
            { name: "Сандал", src: woods.sandalwood },
          ],
          middle: [
            { name: "Мастиковое дерево", src: woods.masticTree },
            { name: "Сосна", src: woods.pine },
            { name: "Гвоздика", src: spices.cloves },
            { name: "Цветок апельсина", src: flowers.orangeBlossom },
            { name: "Амирис", src: woods.amyris },
          ],
          base: [
            { name: "Элеми", src: resins.elemi },
            { name: "Сладкий апельсин", src: fruits.orange },
            { name: "Чёрная смородина", src: berries.blackCurrant },
            { name: "Мускатный орех", src: spices.nutmeg },
            { name: "Дым", src: natural.smoke },
            { name: "Табак", src: green.tobacco },
          ],
        },
        textStory: {
          brandHistory: storyB.reliqvia.brandHistory,
          perfumeHistory: storyB.reliqvia.perfumeHistory,
          review: storyB.reliqvia.review,
        },
        vibe: [
          { name: "Мрачное здание", src: imgVibe },
          { name: "Влажный", src: imgVibe },
          { name: "Тёмный", src: imgVibe },
        ],
      },

      {
        brand: "Filippo Sorcinelli",
        perfumeName: "Lavs",
        promoText: "Металлический ладан",
        imagePerfume: lavsBottle,
        price01ml: 0,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 50,
        price10ml: 100,
        priceFull: 190,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Чёрный перец", src: spices.blackPepper },
            { name: "Кардамон", src: spices.cardamom },
            { name: "Жасмин", src: flowers.jasmine },
          ],
          middle: [
            { name: "Элеми", src: resins.elemi },
            { name: "Лабданум", src: resins.labdanum },
            { name: "Гвоздика", src: spices.cloves },
            { name: "Кориандр", src: spices.coriander },
          ],
          base: [
            { name: "Опопонакс", src: resins.opoponax },
            { name: "Дубовый мох", src: green.moss },
            { name: "Палисандр", src: woods.palisander },
            { name: "Амбра", src: animalistic.amber },
            { name: "Бобы тонка", src: spices.tonkaBean },
          ],
        },
        textStory: {
          brandHistory: storyB.lavs.brandHistory,
          perfumeHistory: storyB.lavs.brandHistory,
          review: storyB.lavs.brandHistory,
        },
        vibe: [
          { name: "Мрачное здание", src: imgVibe },
          { name: "Влажный", src: imgVibe },
          { name: "Тёмный", src: imgVibe },
        ],
      },

      {
        brand: "Filippo Sorcinelli",
        perfumeName: "Chi lo vuole, lo puo riscoprire...",
        promoText: "Новогодний дух",
        imagePerfume: NotIMG,
        price01ml: 0,
        price05ml: 0,
        price1ml: 10,
        price2ml: 20,
        price5ml: 50,
        price10ml: 100,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Металлические ноты", src: natural.metallicNotes },
            { name: "Грейпфрут", src: fruits.grapefruit },
            { name: "Чёрный перец", src: spices.blackPepper },
            { name: "Гальбанум", src: green.galbanum },
          ],
          middle: [
            { name: "Олибанум", src: resins.olibanum },
            { name: "Чёрная роза", src: flowers.blackRose },
            { name: "Лабданум", src: resins.labdanum },
            { name: "Пудровые ноты", src: gourmand.ediblePowder },
          ],
          base: [
            { name: "Кожа", src: animalistic.leather },
            { name: "Масло яванского ветивера", src: balsamsOil.absolutePlants },
            { name: "Дубовый мох", src: green.moss },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Filippo Sorcinelli",
        perfumeName: "Vento Forte",
        promoText: "Резиновая акватика",
        imagePerfume: ventoForteBottle,
        price01ml: 0,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 50,
        price10ml: 100,
        priceFull: 190,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Замша", src: animalistic.suede },
            { name: "Калон", src: synthetics.calone },
            { name: "Дубовый мох", src: green.moss },
          ],
          middle: [
            { name: "Грязь", src: natural.mud },
            { name: "Кожа", src: animalistic.leather },
          ],
          base: [{ name: "Ветер", src: natural.wind }],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: imgVibe },
          { name: "Влажный", src: imgVibe },
          { name: "Тёмный", src: imgVibe },
        ],
      },

      {
        brand: "Filippo Sorcinelli",
        perfumeName: "Contre Bombarde 32",
        promoText: "Древесно сливочная гурманика",
        imagePerfume: bombardeBottle,
        price01ml: 0,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 50,
        price10ml: 100,
        priceFull: 190,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Ваниль", src: spices.vanilla },
            { name: "Амбра", src: animalistic.amber },
          ],
          middle: [
            { name: "Кедровое дерево", src: woods.cedarWood },
            { name: "Сандаловое дерево", src: woods.sandalwood },
          ],
          base: [
            { name: "Можжевельник", src: green.juniper },
            { name: "Элеми", src: resins.elemi },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: imgVibe },
          { name: "Влажный", src: imgVibe },
          { name: "Тёмный", src: imgVibe },
        ],
      },

      {
        brand: "Caeleste",
        perfumeName: "Principalities",
        promoText: "Миниральное печенье",
        imagePerfume: principalitiesBottle,
        price01ml: 0,
        price05ml: 24.9,
        price1ml: 49.9,
        price2ml: 99.9,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Минеральные ноты", src: natural.mineralNotes },
            { name: "Петрикор", src: natural.petrichor },
            { name: "Шипы розы", src: green.roseThorns },
            { name: "Фиалка", src: flowers.violet },
            { name: "Иссоп", src: flowers.hyssop },
            { name: "Чёрный чай", src: drinks.blackTea },
            { name: "Иланг-иланг", src: flowers.ylangYlang },

          ],
          middle: [
            { name: "Уд Ассафи", src: woods.agarwoodOud },
            { name: "Сухие листья", src: natural.dryLeaves },
            { name: "Пепел", src: natural.ash },
            { name: "Корень женьшеня", src: vegetables.ginseng },
            { name: "Элеми", src: resins.elemi },
            { name: "Кожа", src: animalistic.leather },
            { name: "Гальбанум", src: green.galbanum },
            { name: "Бессмертник", src: green.immortelle },               
            { name: "Семена чили", src: vegetables.carrotSeeds },
            { name: "Шафран", src: spices.saffron },
          ],
          base: [
            { name: "Печёное миндальное печенье", src: gourmand.cookie },
            { name: "Звёздная пыль", src: natural.dust },
            { name: "Порох", src: objects.gunpowder },                             
            { name: "Ладан", src: resins.incense },
            { name: "Горячий металл", src: objects.hotIron },
            { name: "Сандал", src: woods.sandalwood },
            { name: "Цветок космея", src: flowers.cosmosFlower },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Toskovat",
        perfumeName: "Inexcusable Evil",
        promoText: "Запах войны",
        imagePerfume: inexcusableBottle,
        price01ml: 0,
        price05ml: 19.9,
        price1ml: 39.9,
        price2ml: 0,
        price5ml: 0.0,
        price10ml: 0.0,
        priceFull: 0.0,
        visibility: "visible",
        volumeMl: 100,
        notes: {
          top: [
            { name: "Порох", src: objects.gunpowder },
            { name: "Озон", src: natural.ozone },
          ],
          middle: [
            { name: "Кровь", src: animalistic.blood },
            { name: "Бинты", src: rare.bandages },
            { name: "Йод", src: natural.iodine },
            { name: "Горящие цветы", src: flowers.burningFlowers },
            { name: "Гваяк", src: woods.guaiacWood },
            { name: "Масло копайбы", src: balsamsOil.copaibaBalsam },
            { name: "Нагармота", src: green.nagarmotha },
          ],
          base: [
            { name: "Обломки бетона", src: rare.fallenConcrete },
            { name: "Дождь", src: natural.rain },
            { name: "Ладан", src: resins.incense },
            { name: "Сандаловое дерево", src: woods.sandalwood },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: imgVibe },
          { name: "Влажный", src: imgVibe },
          { name: "Тёмный", src: imgVibe },
        ],
      },

      {
        brand: "Toskovat",
        perfumeName: "Last Birthday Cake",
        promoText: "Вкус последнего торта",
        imagePerfume: birthdayBottle,
        price01ml: 0,
        price05ml: 19.9,
        price1ml: 39.9,
        price2ml: 79.9,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Ослепительный свет", src: natural.solarNotes },
            { name: "Молоко", src: drinks.milk },
            { name: "Фитиль", src: rare.wick },
            { name: "Растворимое какао", src: gourmand.cocoa },
            { name: "Мирная лилия", src: flowers.lily },
            { name: "Горький миндаль", src: nuts.almond },
            { name: "Пробка", src: rare.cork },
            { name: "Солод", src: vegetables.malt },
          ],
          middle: [
            { name: "Арманьяк", src: drinks.bourbonWhiskey },
            { name: "Штоллен", src: gourmand.cake },
            { name: "Коричневый сахар", src: gourmand.palmSugar },
            { name: "Ванильный крем", src: gourmand.cream },
            { name: "Бобы тонка", src: spices.tonkaBean },
            { name: "Сладкий клевер", src: green.clover },
          ],
          base: [
            { name: "Веревочное ожерелье", src: rare.ropeNecklace },
            { name: "Ружьё Чехова", src: rare.chekhovGun },
            { name: "Стиракс", src: resins.styrax },
            { name: "Кожа", src: animalistic.skin },
            { name: "Толуанский бальзам", src: balsamsOil.toluBalsam },
            { name: "Ладан", src: resins.incense },
            { name: "Абсолют отрубей", src: gourmand.bran },
            { name: "Папирус", src: woods.papyrus },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: imgVibe },
          { name: "Влажный", src: imgVibe },
          { name: "Тёмный", src: imgVibe },
        ],
      },

      {
        brand: "Toskovat",
        perfumeName: "Age of Innocence",
        promoText: "Бензиновая жвачка",
        imagePerfume: NotIMG,
        price01ml: 0,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 50,
        price10ml: 100,
        priceFull: 190,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Жевательная резинка", src: gourmand.bubbleGum },
            { name: "Сахарная вата", src: gourmand.cottonCandy },
            { name: "Клубника", src: berries.strawberry },
          ],
          middle: [
            { name: "Скрежет металла", src: rare.screechingMetal },
            { name: "Резина", src: objects.rubber },
            { name: "Бензин", src: objects.gasoline },
            { name: "Роза", src: flowers.rose },
            { name: "Автомобильные сиденья", src: rare.carSeats },
          ],
          base: [
            { name: "Натуральный уд", src: woods.agarwoodOud },
            { name: "Гаитянский ветивер", src: green.vetiver },
            { name: "Можжевеловое масло", src: balsamsOil.absolutePlants },
            { name: "Кедр", src: woods.cedarWood },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Toskovat",
        perfumeName: "Empty Wishes Well",
        promoText: "xxxxx",
        imagePerfume: NotIMG,
        price01ml: 0,
        price05ml: 19.9,
        price1ml: 39.9,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Брошенная ржавая монета", src: rare.rustyCoin },
          ],
          middle: [
            { name: "Петрикор", src: natural.petrichor },
            { name: "Мирра", src: resins.myrrh },
            { name: "Сухие листья", src: natural.dryLeaves },
            { name: "Пыльный мрамор", src: natural.marble },
            { name: "Шалфей", src: green.clarySage },
          ],
          base: [
            { name: "Почва", src: natural.dirt },
            { name: "Пачули", src: green.patchouli },
            { name: "Яванский и гаитянский ветивер", src: green.vetiver },
            { name: "Амирис", src: woods.amyris },
            { name: "Гальбанум", src: green.galbanum },
            { name: "Семена моркови", src: vegetables.carrot },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Toskovat",
        perfumeName: "Born Screaming",
        promoText: "Дымный",
        imagePerfume: NotIMG,
        price01ml: 0,
        price05ml: 19.9,
        price1ml: 39.9,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Вишня", src: berries.cherry },
            { name: "Ежевика", src: berries.blackberry },
            { name: "Физалис", src: berries.physalis },
            { name: "Энергетик", src: drinks.energyDrink },
            { name: "Футляр для DVD", src: rare.dvdCase },
            { name: "Лопнувший шарик", src: rare.poppedBalloon },
            { name: "Латекс", src: objects.latex },
            { name: "Игрушки для взрослых", src: rare.adultToys },
          ],
          middle: [
            { name: "Дым", src: natural.smoke },
            { name: "Танцевальный клуб", src: rare.danceClub },
            { name: "Дурман", src: flowers.datura },            
            { name: "Роза", src: flowers.rose },
            { name: "Борония", src: flowers.boronia },
            { name: "Резеда", src: green.myrtle },
            { name: "Слюна", src: animalistic.saliva },
            { name: "Гелиотропин", src: synthetics.diviniris },
          ],
          base: [
            { name: "Мирра", src: resins.myrrh },
            { name: "Стиракс", src: resins.styrax },
            { name: "Фрезия", src: flowers.freesia },
            { name: "Древесина кабрувы", src: woods.palisander },
            { name: "Пачули", src: green.patchouli },
            { name: "Кастореум", src: animalistic.castoreum },
            { name: "Амбретта", src: animalistic.ambrette },
            { name: "Жемчужное ожерелье", src: rare.pearlNecklace },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: imgVibe },
          { name: "Влажный", src: imgVibe },
          { name: "Тёмный", src: imgVibe },
        ],
      },

      {
        brand: "Toskovat",
        perfumeName: "Generation Godard",
        promoText: "xxxxx",
        imagePerfume: NotIMG,
        price01ml: 0,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 50,
        price10ml: 100,
        priceFull: 190,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Старый кинотеатр", src: rare.cinema },
            { name: "Кислые конфеты", src: gourmand.bubbleGum },
          ],
          middle: [
            { name: "Попкорн застрявший в зубах", src: rare.popcornMouth },
            { name: "Кока-кола", src: drinks.cocaCola },
            { name: "Картонные стаканчики", src: rare.cardboardCups },
            { name: "Роза", src: flowers.rose },
          ],
          base: [
            { name: "Газета", src: rare.newspaper },
            { name: "Сигаретные фильтры", src: rare.cigarettes },
            { name: "Мускус", src: animalistic.musk },
            { name: "Лабданум", src: resins.labdanum },
            { name: "Амбретта", src: animalistic.ambrette },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Toskovat",
        perfumeName: "Anarchist A_",
        promoText: "xxxxx",
        imagePerfume: NotIMG,
        price01ml: 0,
        price05ml: 19.9,
        price1ml: 39.9,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Кредитные карты", src: rare.creditCards },
            { name: "Снег", src: natural.snow },
            { name: "Виски", src: drinks.bourbonWhiskey },
          ],
          middle: [
            { name: "Грязные доллары", src: objects.money },
            { name: "Чернила", src: objects.ink },
            { name: "Воск свечи", src: objects.candle },
          ],
          base: [
            { name: "Зелёная сакральная смола", src: resins.greenResin },
            { name: "Святая вода", src: rare.holyWater },
            { name: "Старая исповедальня", src: rare.confessional },
            { name: "Одежда священника", src: rare.priestClothes },
            { name: "Полиэтиленовый пакет", src: rare.plasticBag },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Nasomatto",
        perfumeName: "Fantomas",
        promoText: "Призрак дыни",
        imagePerfume: fantomasBottle,
        price01ml: 0,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 50,
        price10ml: 100,
        priceFull: 190,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Дыня", src: fruits.melon },
            { name: "Резина", src: objects.rubber },
            { name: "Пластик", src: objects.plastic },
          ],
          middle: [
            { name: "Дым", src: natural.smoke },
            { name: "Порох", src: objects.gunpowder },
            { name: "Карамель", src: gourmand.caramel },
          ],
          base: [
            { name: "Земля", src: natural.earthyNotes },
            { name: "Кашмеран", src: synthetics.cashmeran },
            { name: "Тропические фрукты", src: fruits.fruityNotes },
            { name: "Пачули", src: green.patchouli },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Pictura Fragrans",
        perfumeName: "Naju Spring",
        promoText: "Мороженое",
        imagePerfume: "",
        price01ml: 5.9,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Имбирь", src: spices.ginger },
            { name: "Грушевое мороженое", src: gourmand.pearIceCream },
            { name: "Матча", src: drinks.mate },
            { name: "Миндаль", src: nuts.almond },
          ],
          middle: [
            { name: "Рис", src: gourmand.rice },
            { name: "Белый табак", src: green.tobacco },
            { name: "Хиноки", src: woods.hinokiWood },
            { name: "Белые цветы", src: flowers.whiteFlowers },
            { name: "Жасмин", src: flowers.jasmine },
          ],
          base: [
            { name: "Корейское барбекю", src: gourmand.bbq },
            { name: "Кастореум", src: animalistic.castoreum },
            { name: "Сандал", src: woods.sandalwood },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Pictura Fragrans",
        perfumeName: "Surinam Vert",
        promoText: "Бензиновые фрукты",
        imagePerfume: "",
        price01ml: 0,
        price05ml: 1,
        price1ml: 0,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Гуава", src: fruits.guava },
            { name: "Зелень", src: green.greenNotes },
            { name: "Маракуйя", src: fruits.passionfruit },
            { name: "Кокосовая вода", src: drinks.coconutMilk },
            { name: "Бензин", src: objects.gasoline },
          ],
          middle: [
            { name: "Тёплый дождь", src: natural.rain },
            { name: "Орхидея", src: flowers.orchid },
            { name: "Франжипани", src: flowers.frangipani },
            { name: "Магнолия", src: flowers.magnolia },
            { name: "Мёд", src: gourmand.honey },
            { name: "Гелиотроп", src: flowers.heliotrope },
            { name: "Зелёный лес", src: woods.forestTrees },
            { name: "Гардения", src: flowers.gardenia },
            { name: "Земля", src: natural.earthyNotes },
            { name: "Петрикор", src: natural.petrichor },
          ],
          base: [
            { name: "Джунглевый мох", src: green.moss },
            { name: "Амбра", src: animalistic.amber },
            { name: "Толуанский бальзам", src: balsamsOil.toluBalsam },
            { name: "Перуанский бальзам", src: balsamsOil.peruBalsam },
            { name: "Ночной жасмин", src: flowers.jasmine },
            { name: "Мускус", src: animalistic.musk },
            { name: "Кашмеран", src: synthetics.cashmeran },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Pictura Fragrans",
        perfumeName: "Lux Obscura",
        promoText: "xxxxx",
        imagePerfume: NotIMG,
        price01ml: 0,
        price05ml: 1,
        price1ml: 0,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Глина", src: natural.clay },
            { name: "Порох", src: objects.gunpowder },
            { name: "Копчёная паприка", src: spices.pinkPepper },
            { name: "Йод", src: natural.iodine },
            { name: "Дождь", src: natural.rain },
            { name: "Кровь", src: animalistic.blood },         
            { name: "Имбирь", src: spices.ginger },
            { name: "Лист магнолии", src: green.foliage },
          ],
          middle: [
            { name: "Мак", src: flowers.poppy },
            { name: "Пачули", src: green.patchouli },         
            { name: "Клирвуд", src: woods.clearwood },
            { name: "Гвоздика", src: flowers.carnation },
            { name: "Шафран", src: spices.saffron },
            { name: "Чёрный чай", src: drinks.blackTea },
            { name: "Табак", src: green.tobacco },
            { name: "Цветок чёрной смородины", src: flowers.cheeryBlossom },
          ],
          base: [
            { name: "Деревянная бочка", src: objects.barrel },
            { name: "Акигалавуд", src: synthetics.akigalawood },
            { name: "Абсолют сандала", src: balsamsOil.woodOil },
            { name: "Орканокс", src: synthetics.orcanox },     
            { name: "Опопонакс", src: resins.opoponax },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Pictura Fragrans",
        perfumeName: "The Serpent's Orchard",
        promoText: "xxxxx",
        imagePerfume: "",
        price01ml: 0,
        price05ml: 1,
        price1ml: 0,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Инжирное дерево", src: woods.figWood },
            { name: "Крапива", src: green.nettle },
            { name: "Лист инжира", src: green.figLeaf },
            { name: "Слива", src: fruits.plum },
            { name: "Токайское вино", src: drinks.champagne },
            { name: "Роза альба", src: flowers.rose },
          ],
          middle: [
            { name: "Спелый инжир", src: fruits.fig },
            { name: "Йогурт", src: gourmand.yogurt },
            { name: "Жасмин самбак", src: flowers.jasmine },
            { name: "Мёд", src: gourmand.honey },
            { name: "Мирра", src: resins.myrrh },
          ],
          base: [
            { name: "Мускон", src: synthetics.muscone },
            { name: "Майсурский сандал", src: woods.sandalwood },
            { name: "Индол", src: synthetics.indole },
            { name: "Мацис", src: spices.mace },
            { name: "Мускус", src: animalistic.musk },
            { name: "Амбра", src: animalistic.amber },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Pictura Fragrans",
        perfumeName: "Elysee Liminaire",
        promoText: "Индустриальная зелень",
        imagePerfume: "",
        price01ml: 5.9,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Металлические ноты", src: natural.metallicNotes },
            { name: "Водка", src: drinks.vodka },
            { name: "Сгоревшая спичка", src: objects.burntMatch },
            { name: "Помело", src: fruits.pomelo },
            { name: "Порох", src: objects.gunpowder },
            { name: "Резина", src: objects.rubber },
          ],
          middle: [
            { name: "Магнолан", src: synthetics.magnolan },
            { name: "Вода", src: natural.water },
            { name: "Гексенил зелёный", src: synthetics.hexenylGreen },
            { name: "Борония", src: flowers.boronia },
            { name: "Жасмин", src: flowers.jasmine },
            { name: "Шисо", src: green.shiso },
            { name: "Белый лотос", src: flowers.lotus },
            { name: "Кардамон", src: spices.cardamom },
          ],
          base: [
            { name: "Прополис", src: resins.propolis },
            { name: "Уд", src: woods.agarwoodOud },
            { name: "Сандал", src: woods.sandalwood },
            { name: "Животные ноты", src: animalistic.animalNotes },
            { name: "Парадизон", src: synthetics.paradisone },
            { name: "Мускус", src: animalistic.musk },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Bohoboco",
        perfumeName: "Plum Spray Paint",
        promoText: "Слива в краске",
        imagePerfume: "",
        price01ml: 0,
        price05ml: 9.9,
        price1ml: 0,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Розовый перец", src: spices.pinkPepper },
            { name: "Слива", src: fruits.plum },
            { name: "Аэрозольная краска", src: objects.sprayPaint },
            { name: "Корица", src: spices.cinnamon },
          ],
          middle: [
            { name: "Шафран", src: spices.saffron },
            { name: "Магнолия", src: flowers.magnolia },
            { name: "Красные ягоды", src: berries.redBerries },
            { name: "Жасмин", src: flowers.jasmine },
            { name: "Ром", src: drinks.rum },
          ],
          base: [
            { name: "Лабданум", src: resins.labdanum },
            { name: "Виски", src: drinks.bourbonWhiskey },
            { name: "Пачули", src: green.patchouli },
            { name: "Кожа", src: animalistic.leather },
            { name: "Дым", src: natural.smoke },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Bohoboco",
        perfumeName: "Mango Yuzu Gasoline",
        promoText: "Манго в бензине",
        imagePerfume: "",
        price01ml: 0,
        price05ml: 9.9,
        price1ml: 0,
        price2ml: 0,
        price5ml: 50,
        price10ml: 100,
        priceFull: 190,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Манго", src: fruits.mango },
            { name: "Ананас", src: fruits.pineapple },
            { name: "Мандарин", src: fruits.mandarin },
            { name: "Юдзу", src: fruits.yuzu },
            { name: "Каламондин", src: fruits.calamondin },
            { name: "Чёрная смородина", src: berries.blackCurrant },
          ],
          middle: [
            { name: "Ландыш", src: flowers.lilyValley },
            { name: "Ирис", src: flowers.iris },
            { name: "Жасминовый чай", src: drinks.jasmineTea },
            { name: "Бразильское манго", src: fruits.mango },
          ],
          base: [
            { name: "Бензин", src: objects.gasoline },
            { name: "Ладан", src: resins.incense },
            { name: "Замша", src: animalistic.suede },
            { name: "Кожа", src: animalistic.leather },
            { name: "Кедр", src: woods.cedarWood },
            { name: "Мшистые ноты", src: green.moss },
            { name: "Ветивер", src: green.vetiver },
            { name: "Амбра", src: animalistic.amber },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Ataraxia",
        perfumeName: "Amaretto Jazz in the Melting Room",
        promoText: "xxxxx",
        imagePerfume: "",
        price01ml: 0,
        price05ml: 1,
        price1ml: 0,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Амаретто", src: drinks.amaretto },
            { name: "Литургический хлеб", src: gourmand.bread },
          ],
          middle: [
            { name: "Ликёр из чёрной вишни", src: drinks.redWine },
            { name: "Амаретто", src: drinks.amaretto },
            { name: "Мёд", src: gourmand.honey },
            { name: "Свечной воск", src: objects.candle },
            { name: "Кофейные зёрна", src: drinks.coffee },
          ],
          base: [
            { name: "Шоколад с фундуком", src: gourmand.darkChocolate },
            { name: "Коньяк", src: drinks.bourbonWhiskey },
            { name: "Миндаль", src: nuts.almond },
            { name: "Пыльный диван", src: rare.sofa },
            { name: "Страстоцвет", src: flowers.passionFlower },
            { name: "Масло какао", src: gourmand.cacaoButter },
            { name: "Соты", src: animalistic.beeswax },
            { name: "Ванильная икра", src: spices.vanillaCaviar },
            { name: "Табачный абсолют", src: balsamsOil.absolutePlants },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },

      {
        brand: "Ataraxia",
        perfumeName: "Deity",
        promoText: "xxxxx",
        imagePerfume: NotIMG,
        price01ml: 1,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Мёд", src: gourmand.honey },
            { name: "Крем Шантийи", src: gourmand.cream },
            { name: "Японская слива", src: fruits.plum },
            { name: "Вишнёвый джем", src: gourmand.jam },         
            { name: "Физалис", src: berries.physalis },
          ],
          middle: [
            { name: "Абсолют пчелиного воска", src: animalistic.beeswax },
            { name: "Сгущённое молоко", src: gourmand.condensedMilk },
            { name: "Абсолют табака", src: balsamsOil.absolutePlants },
            { name: "Светлый табак", src: green.tobacco },
            { name: "Масло какао", src: gourmand.cacaoButter },         
            { name: "Подснежники", src: flowers.snowdrops },
          ],
          base: [
            { name: "Абсолют олибанума", src: resins.olibanum },
            { name: "Абсолют лабданума", src: resins.labdanum },
            { name: "Бензоин", src: resins.benzoin },
            { name: "Элеми", src: resins.elemi },
            { name: "Мирра", src: resins.myrrh },
            { name: "Тёмное какао", src: gourmand.cocoa },
            { name: "Ваниль", src: spices.vanilla },
            { name: "Бобы тонка", src: spices.tonkaBean },
            { name: "Амбра", src: animalistic.amber },
            { name: "Золото", src: natural.gold },
            { name: "Пачули", src: green.patchouli },
            { name: "Финики", src: fruits.dates },
            { name: "Нектар", src: gourmand.nectar },
          ],
        },
        textStory: {
          brandHistory: [{ text: "Первый абзац" }],
          perfumeHistory: [{ text: "Первый абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "xxx", src: "" },
          { name: "xxx", src: "" },
          { name: "xxx", src: "" },
        ],
      },

      {
        brand: "Hilde Soliani",
        perfumeName: "Miss Tranchant",
        promoText: "xxxxx",
        imagePerfume: NotIMG,
        price01ml: 4.9,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Сливочное масло", src: gourmand.butter },
          ],
          middle: [
            { name: "Шафран", src: spices.saffron },
          ],
          base: [
            { name: "Соль", src: natural.salt },
            { name: "Устрицы", src: animalistic.oysters },
          ],
        },
        textStory: {
          brandHistory: [{ text: "Первый абзац" }],
          perfumeHistory: [{ text: "Первый абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "xxx", src: "" },
          { name: "xxx", src: "" },
          { name: "xxx", src: "" },
        ],
      },

      {
        brand: "Comme des Garcons",
        perfumeName: "CDG",
        promoText: "Парфюмерный клей",
        imagePerfume: NotIMG,
        price01ml: 4.9,
        price05ml: 0,
        price1ml: 0,
        price2ml: 0,
        price5ml: 0,
        price10ml: 0,
        priceFull: 0,
        visibility: "visible",
        volumeMl: 10,
        notes: {
          top: [
            { name: "Альдегиды", src: synthetics.aldehydes },
            { name: "Сафралейн", src: synthetics.diviniris },
            { name: "Боярышник", src: green.hawthorn },
          ],
          middle: [
            { name: "Промышленный клей", src: objects.glue },
            { name: "Скотч", src: objects.scotch },
            { name: "Оксид цветов сирени", src: balsamsOil.absolutePlants },
          ],
          base: [
            { name: "Мускус", src: animalistic.musk },
            { name: "Стиракс", src: resins.styrax },
          ],
        },
        textStory: {
          brandHistory: [
            { text: "Первый абзац" },
            { text: "Второй абзац" },
            { text: "Третий абзац" },
          ],
          perfumeHistory: [{ text: "Первый абзац" }, { text: "Второй абзац" }],
          review: [{ text: "Первый абзац" }],
        },
        vibe: [
          { name: "Мрачное здание", src: "" },
          { name: "Влажный", src: "" },
          { name: "Тёмный", src: "" },
        ],
      },
      
    ],
  },
];

export { perfumesTierB };
